name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
jobs:
  release: # 运行环境
    runs-on: ubuntu-latest
    steps: # 切换到对应 tag 源码
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{secrets.TOKEN}}
          make_latest: true
