name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branchs:
      - main
jobs:
  release: # 运行环境
    runs-on: ubuntu-latest
    steps: # 切换到对应 tag 源码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 安装 Go 
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        # 使用 goreleaser 编译 release
      - name: Create release on GitHub
        uses: goreleaser/goreleaser-action@v6
        with: # GoReleaser 版本
          version: latest # 传递给 GoReleaser 的参数
          args: release --clean
          env: # 提供访问仓库token
            GITHUB_TOKEN: ${{secrets.TOKEN}}
